---
title: "DSC520_FinalProject_Deibler"
author: "Ashley Deibler"
date: "`r Sys.Date()`"
output: pdf_document
---
# create variables
```{r}
catdogdata <- aas_catdogdata
head(catdogdata)

id <- catdogdata$ID
species <- catdogdata$species
breed <- catdogdata$breed
condition_intake <- catdogdata$intake_condition
sex_outcome <- catdogdata$sex_outcome
age_intake <- catdogdata$age_intake_days
age_outcome <- catdogdata$age_outcome_days
time_shelter <- catdogdata$time_shelter_days
outcome_type <- catdogdata$outcome_type
outcome_sub <- catdogdata$outcome_subtype
```

# boxplot for outcome v age
```{r}
install.packages("ggplot2")
library("ggplot2")
install.packages("tidyverse")
library(tidyverse)
install.packages("dplyr")
library(dplyr)

adoption = filter(catdogdata, outcome_type=="Adoption")
died = filter(catdogdata, outcome_type=="Died")
missing = filter(catdogdata, outcome_type=="Missing")
return_owner = filter(catdogdata, outcome_type=="Return to Owner")
euthanasia = filter(catdogdata,outcome_type=="Euthanasia")
transfer = filter(catdogdata, outcome_type=="Transfer")


out_age_bp <- ggplot() +
  geom_boxplot(data = adoption, mapping = aes(x =outcome_type, y = age_outcome_days),
               col = 'blue') +
  geom_boxplot(data = transfer, mapping = aes(x =outcome_type, y = age_outcome_days),
               col = 'lightgreen') +
  geom_boxplot(data = euthanasia, mapping = aes(x =outcome_type, y = age_outcome_days),
               col = 'red') + 
  geom_boxplot(data = died, mapping = aes(x =outcome_type, y = age_outcome_days),
               col = 'black') +
  geom_boxplot(data = missing, mapping = aes(x =outcome_type, y = age_outcome_days),
               col = 'magenta') +
  geom_boxplot(data = return_owner, mapping = aes(x =outcome_type, y = age_outcome_days),
               col = 'purple')+
  theme_classic() +
  labs(title = "Age vs Outcome",
       x = "Outcome",
       y = "Age (days)") + 
  theme(plot.title = element_text(size = 16, 
                                  face = "bold",
                                  hjust = 0.5))

out_age_bp
```

# barplot for reproductive status v outcome
``` {r}
library(ggplot2)

outcome <- rbind(adoption, died, transfer, missing, return_owner, euthanasia)

intactmale = filter(outcome, sex_outcome=="Intact Male")
neuteredmale = filter(outcome, sex_outcome=="Neutered Male")
intactfemale = filter(outcome, sex_outcome=="Intact Female")
spayedfemale = filter(outcome, sex_outcome=="Spayed Female")


repro_stat <- rbind(intactfemale, spayedfemale, intactmale, neuteredmale)

repro_bar <- ggplot(repro_stat, aes(x = outcome_type, fill = sex_outcome)) +
  geom_bar(position = 'dodge', width = 0.7) +
  scale_fill_manual(values = c("pink", 
                               "lightblue",
                               "darkblue",
                               "hotpink")) +
  labs(title = "Reproductive Status vs Outcome",
       x = "Outcome",
       y = "Count",
       fill = "Sex") +
  theme_classic() +
  theme(plot.title = element_text(size = 16, 
                                  face = "bold",
                                  hjust = 0.5))

repro_bar
```


# barplot for outcome v species
```{r}
##Packages
library(ggplot2)

##Create Barplot
species_bar <- ggplot(outcome, aes(x = outcome_type, fill = species)) +
  geom_bar(position = 'dodge', width = 0.8) +
  scale_fill_manual(values = c("orange",
                               "royalblue")) +
  labs(title = "Species vs Outcome",
       x = "Outcome",
       y = "Count",
       fill = "Species") +
  theme_classic() +
  theme(plot.title = element_text(size = 16,
                                  face = "bold",
                                  hjust = 0.5))

species_bar
```


# histogram for distribution of ages from adopted individuals
```{r}
##Packages

library(ggplot2)
library(dplyr)

##Create Histogram

agehist <- ggplot(data = adoption, mapping = aes(x = age_outcome_days)) +
  geom_histogram(bins = 50, binwidth = 200,
                 color = "black", fill = "blue") +
labs(title = "Age of Adopted Animals (days)",
       x = "Age (days)",
       y = "Number of Animals") +
  theme_classic() +
  theme(plot.title = element_text(size = 16,
                                  face = "bold",
                                  hjust = 0.5))
agehist


```

# histogram for distribution of ages and those returned to their owners

```{r}
##Packages

library(ggplot2)
library(dplyr)

##Create Histogram

rto_hist <- ggplot(data = return_owner, mapping = aes(x = age_outcome_days)) +
  geom_histogram(bins = 50, binwidth = 300,
                 color = "black", fill = "purple") +
labs(title = "Age of Animals Returned to Their Owners (days)",
       x = "Age (days)",
       y = "Number of Animals") +
  theme_classic() +
  theme(plot.title = element_text(size = 14,
                                  face = "bold",
                                  hjust = 0.5))
rto_hist

```

# pie chart for reasons behind euthanaia
```{r}
##Create Data Frame

#Count Suffering
value_suff <- "Suffering"
count_suffering <- length(which(euthanasia$outcome_subtype == value_suff))
count_suffering #2006

#Count At Vet
value_vet <- "At Vet"
count_vet <- length(which(euthanasia$outcome_subtype==value_vet))
count_vet #35

#Count Rabies
value_rabies <- "Rabies Risk"
count_rabies <- length(which(euthanasia$outcome_subtype==value_rabies))
count_rabies #149

#Count Medical
value_med <- "Medical"
count_med <- length(which(euthanasia$outcome_subtype==value_med))
count_med #118

#Count Aggressive
value_agg <- "Aggressive"
count_agg <- length(which(euthanasia$outcome_subtype==value_agg))
count_agg #496

#Count Court Investigation
value_court <- "Court/Investigation"
count_court <- length(which(euthanasia$outcome_subtype==value_court))
count_court #23

reason = c("Suffering", "Rabies Risk", "Aggressive", "At Vet", "Medical", "Court/Investigation")
value = c(2006, 149, 496, 35, 118, 23)
reasons_euth <- data.frame(reason, value)

##Create Blank Theme
blank_theme <- theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid = element_blank(),
    axis.ticks = element_blank(),
    plot.title = element_text(size = 14, face = "bold"))

##Packages
library(dplyr)
library(ggplot2)
install.packages("ggrepel")
library(ggrepel)
library(forcats)
library(scales)

##Create Pie Chart

reasons_euth %>%
  arrange(desc(value)) %>%
  mutate(prop = percent(value/sum(value))) -> reasons_euth

euth_pie <- ggplot(reasons_euth, aes(x = "", y = value, fill = fct_inorder(reason))) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  geom_label_repel(aes(label = prop), size = 5, show.legend = F, nudge_x = 1) +
  guides(fill = guide_legend(title = "Reason for Euthanasia")) +
  labs(title = "Proportion of Reasons for Euthanasia") +
  scale_fill_manual(values = c("red","orange","yellow", "green","blue","purple")) +
  blank_theme +
  theme(axis.text.x = element_blank())

euth_pie

```

# barplot for intake condition and outcome
```{r}
##Packages
library(ggplot2)
library(dplyr)
  

condition_intake
normal = filter(outcome, intake_condition=="Normal")
injured = filter(outcome, intake_condition=="Injured")
sick = filter(outcome, intake_condition=="Sick")
aged = filter(outcome, intake_condition== "Aged")
nursing = filter(outcome, intake_condition=="Nursing")
feral = filter(outcome, intake_condition=="Feral")

condition <- rbind(normal, injured, sick, aged, nursing, feral)

con_euth <- filter(condition, outcome_type=="Euthanasia")

con_euth_bar <- ggplot(con_euth, aes(x = intake_condition)) +
  geom_bar(position = 'dodge', width = 0.8, fill = 'darkgreen') +
  labs(title = "Intake Condition of Euthanized Animals",
       x = "Condition",
       y = "Count") +
  theme_classic() +
  theme(plot.title = element_text(size = 16,
                                  face = "bold",
                                  hjust = 0.5))

con_euth_bar

## Create Bar plot
```
